# Generated by Django 4.0.3 on 2022-03-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sampleitems',
            fields=[
                ('sItem', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('sName', models.CharField(max_length=50)),
                ('sDescription', models.TextField(max_length=200)),
            ],
        ),
    ]
